config/routes.rb
Rails.application.routes.draw do
  
  resources :messages, only: [:new, :create]

  resources :contacts, only: [:new, :create]
  post 'contacts/new'
  resources :projects
  devise_for :users, controllers: { sessions: "users/sessions" }

  get 'confrencedet/main'

  get 'confrencedet/speakers'

  get 'confrencedet/fees'

  get 'confrencedet/presentation'

  get 'confrencedet/venue'
  get 'confrencedet/advert'

  get 'confrencedet/sponsorship'

  get 'confrencedet/abstractdetails'

  resources :abstracts
  resources :sponsors
  resources :conferences do
      resources :papers, except: [:show, :index]
  end

  get 'welcome/main'
  get 'welcome/donation'
  
  get 'welcome/profile'

  get 'welcome/index'
  get 'welcome/about'
  

 root 'welcome#index'

end

app/models/conference.rb
class Conference < ActiveRecord::Base
    belongs_to :user
    has_many :papers
    validates :organisation, :position, :address, :city, :country, :postcode, :telephone, :presence => true
    
    
    def admin?
        
        admin :true
        
    end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /conferences
  # GET /conferences.json
  def index
    if current_user && !current_user.admin?
      @conferences = Conference.where(user_id: current_user)
    
    else
      @conferences = Conference.all
    end
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
    @papers = Paper.where(conference_id: @conference.id).order("created_at DESC")
  end

  # GET /conferences/new
  def new
    @conference = current_user.conferences.build
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = current_user.conferences.build(conference_params)

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render :show, status: :created, location: @conference }
      else
        format.html { render :new }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    respond_to do |format|
      if @conference.update(conference_params)
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { render :show, status: :ok, location: @conference }
      else
        format.html { render :edit }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url, notice: 'Conference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def main
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:organisation, :position, :address, :postcode, :city, :country, :telephone)
    end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<div class="container">
        <div class="row centered-form">
          <div class="col-lg-6">
                <div class="well well-sm"><strong><span class="glyphicon glyphicon-asterisk"></span>Required Field</strong></div>
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> need to be fixed to save</h2>

      <ul>
      <% @conference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <label for="InputName"><%= f.label :organisation%><br></label>
  <div class="input-group">
    
    <%= f.text_field :organisation, class: "form-control"  %>
    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
  </div>
  <label for="InputName"><%= f.label :position%><br></label>
  <div class="input-group">

    <%= f.text_field :position, class: "form-control" %>
    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
  </div>
  <label for="InputName"><%= f.label :address%><br></label>
  <div class="input-group">
    <%= f.text_area :address, class: "form-control" %>
    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span> 
  </div>
  <label for="InputName"><%= f.label :postcode%>/Zipcode<br></label>
  <div class="input-group">
    <%= f.text_field :postcode, class: "form-control" %>
    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
  </div>
  <label for="InputName"><%= f.label :city%><br></label>
  <div class="input-group">
    <%= f.text_field :city, class: "form-control" %>
    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
  </div>
  <label for="InputName"><%= f.label :country%><br></label>
  <div class="input-group">
    <%= f.text_field :country, class: "form-control" %>
    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
  </div>
  <label for="InputName"><%= f.label :telephone%><br></label>
  <div class="input-group">
    <%= f.text_field :telephone, class: "form-control" %>
    <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div></div></div></div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing Conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<% if current_user && !current_user.admin? %>
			 <div class="panel panel-default">
        <div class="panel-heading">
<div class="widget stacked widget-table action-table">
    				
				<div class="widget-header">
					<i class="icon-th-list"></i>
					<h3>Applications</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">

<table class="table table-responsive table-striped table-bordered">
  <thead>
    <tr>
      <th>Organisation/ Institution</th>

      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%=  %><%= link_to conference.organisation, conference %></td>
        <td><%= time_ago_in_words(Time.now) %></td>
        <td><%= link_to 'Update', edit_conference_path(conference), class: "btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

	</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->
  

<% else %>
<div class="widget stacked widget-table action-table">
    				
				<div class="widget-header">
					<i class="icon-th-list"></i>
					<h3>Conference Applicant</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">

<table class="table table-responsive table-striped table-bordered">
  <thead>
    <tr>
      <th>Organisation</th>
      <th>Position</th>
      <th>City</th>
      <th>Country</th>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%= conference.organisation %></td>
        <td><%= conference.position %></td>
        <td><%= conference.city %></td>
        <td><%= conference.country %></td>
        <td><%= conference.telephone %></td>
        <td><%= link_to 'Show', conference %></td>
        <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
        <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

	</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->
  


			 
<%  end %>

app/views/conferences/new.html.erb
<h1>Apply to Conference</h1>
<p>You will be able to submit an abstract after filling this form</p>

<%= render 'form' %>

app/views/conferences/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">

        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Organisation:</strong></td>
                <td> <%= @conference.organisation %></td>
              </tr>
              <tr>
                <td><strong>Position:</strong></td>
                <td><%= @conference.position %></td>
              </tr>
              <tr>
                <td><strong>Telephone:</strong></td>
                <td><%= @conference.telephone %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="conf_title"><%= @conference.organisation %></h1>
        
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Address:</strong></td>
                <td> <%= @conference.address %></td>
              </tr>
              <tr>
                <td><strong>City:</strong></td>
                <td><%= @conference.city %></td>
              </tr>
              <tr>
                <td><strong>Zip / Postcode:</strong></td>
                <td><%= @conference.postcode %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Pay Admission Fees", conference_path, class: "btn btn-primary" %><%= link_to 'Destroy', conference_path(@conference), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %><%= link_to 'Update', edit_conference_path(@conference), class: "btn btn-info" %><br/>
          <h1>Abstract</h1>
          <% if @papers.blank? %>
             <h3>Submit your abstract for review on or before june 9</h3>
             <%= link_to "Submit an Abstract", new_conference_paper_path(@conference), class: "btn btn-success" %>
          <% else %>
             <%= @papers.each do |paper| %>
              <div>
                <p><%= paper.title %></p>
                <p><%= paper.content %></p>
                <p><%= paper.status %></p>
              </div>
              <% end %>
          <% end %>
             
        </div>
       
    </div>
  </div>
</div></div>