config/routes.rb
Rails.application.routes.draw do
  
  resources :messages, only: [:new, :create]

  resources :contacts, only: [:new, :create]
  post 'contacts/new'
  resources :projects
  devise_for :users, controllers: { sessions: "users/sessions" }

  get 'confrencedet/main'

  get 'confrencedet/speakers'

  get 'confrencedet/fees'

  get 'confrencedet/presentation'

  get 'confrencedet/venue'
  get 'confrencedet/advert'

  get 'confrencedet/sponsorship'

  get 'confrencedet/abstractdetails'

  resources :abstracts
  resources :sponsors
  resources :conferences do
      resources :papers, except: [:show, :index]
  end

  get 'welcome/main'
  get 'welcome/donation'
  
  get 'welcome/profile'

  get 'welcome/index'
  get 'welcome/about'
  

 root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def donation
  end

  def index
  end
  
  def about
  end
  
  def main
   
    
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>Financial Report</h1>
<p>You can download our financial report for 2016 <a><%= link_to "here", "https://drive.google.com/open?id=0ByZuGkVpeqIQOEZVNFdTUWdzakE", :target => "_blank" %></a></p>

app/views/welcome/donation.html.erb
<div class="container">
    <div class="col-md-3 col-lg-3">
        <div class="well">
            <h3>Share Our Vision</h3>
            <p>Help us in our mission by supporting our projects. 
            Join us to emancipate the SEN. Kindly assist us by contributing towards the projects.
            The projects are presented below and there are more details on the project menu. 
            Kindly deposit all donations directly into our bank account and send the evidence of payment to admin@scitec4sen.com.
            All donations will be acknowledged by an official receipt</p>
            <h3>Check Out Some of the projects we are working on</h3>
            <%= link_to "Projects", confrencedet_main_path, class: "btn btn-primary" %>
        </div>
    </div>
     
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title">Banking Details for Donations</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                  <div class="col-md-9 col-lg-9">
<p>

Donations toward the projects of the organisations should be paid into: </p>

<p><strong>Name of Account:</strong> Science and Technology for Nigeria Persons with Special Needs Initiative</p>

<p><strong>Name of Bank:</strong> Guaranty Trust Bank, Owode, Oyo Nigeria</p>

<p><strong>Account Number:</strong> 0201171027</p>

<p>Bic (SWIFT)         gtbingla</p>

<p>PLEASE E-MAIL COPY OF EVIDENCE OF PAYMENT TO admin@scitec4sen.com and remember to indicate the specific project in mind of the Donor. Thank you</p>

</div></div>
</div>
</div>
</div>
</div>

app/views/welcome/index.html.erb
 <!-- Full Width Image Header -->
    <header class="header-image">
        <div class="headline">
            <div class="container">
                
                <h2>Science Should be for all</h2>
                <h1>Irespective of Disability</h1>
            </div>
        </div>
    </header>
     <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header" style="color: #265894">
                    Welcome to Scitec4sen
                </h1>
            </div>
            <div class="col-md-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i> Ongoing Event </h4>
                    </div>
                    <div class="panel-body">
                        <p>SCIENTIFIC SIGN LANDUAGE DEVELOPMENT PROJECT </p>
                        <h4>Annual Science Camp</h4>
                        <p>The organisation is planning a national Camp for learners with visual impairment in secondary schools. Complete the Contact us page 
                        if you would like to Sponsor/Participate. You can also visit the event website</p>
                        <h4>Training</h4>
                        <p>Our instructors are chosen for their enthusiasm, dedication, commitment, and desire to empower and encourage learners with Special Needs in STEM.</p>
                       
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-compass"></i> About Us</h4>
                    </div>
                    <div class="panel-body">
                        <p>The Science and Technology for Nigeria Persons with Special Needs Initiative[scitec4sen] focuses on enabling access of STEM disciplines to Persons with Special Educational Needs. </p>
                        
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i>Previous Events</h4>
                    </div>
                    <div class="panel-body">
                        <p><strong>International Conference    August, 2016  </strong> </p>
<p> Annual Science Camp for learners with visual impairment.     December, 2016</p>
<p>Training   TBA</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
        

    <!-- Features Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Projects</h2>
            </div>
            <div class="col-md-6">
              <h1></h1>
             
               </div>
            <div class="col-md-6">
                <img class="img-responsive" src="#" alt="">
            </div>
        </div>
        <!-- /.row -->
        </div>

app/views/welcome/main.html.erb
<% if current_user && current_user.admin? %>
			 <div class="panel panel-default">
        <div class="panel-heading">
<div class="widget stacked widget-table action-table">
    				
				<div class="widget-header">
					<i class="icon-th-list"></i>
					<h3>Conference Applicant</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">

<table class="table table-responsive table-striped table-bordered">
  <thead>
    <tr>
      <th>Organisation</th>
      <th>Position</th>
      <th>City</th>
      <th>Countryjjjjjj</th>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <td><%= conference.organisation %></td>
        <td><%= conference.position %></td>
        <td><%= conference.city %></td>
        <td><%= conference.country %></td>
        <td><%= conference.telephone %></td>
        <td><%= link_to 'Show', conference %></td>
        <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
        <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

	</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->
  

<% end %>

app/views/welcome/profile.html.erb
<div class="container">
      <div class="row">
      <div class="col-md-9  toppad  pull-right col-md-offset-3 ">
           <A><%= link_to "Edit Profile", edit_user_registration_path %></A>|

        <A><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></A>
       <br>
<p class=" text-info"><%= Date.today %> </p>

      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= current_user.name %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
                
                <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
                  <dl>
                    <dt>DEPARTMENT:</dt>
                    <dd>Administrator</dd>
                    <dt>HIRE DATE</dt>
                    <dd>11/12/2013</dd>
                    <dt>DATE OF BIRTH</dt>
                       <dd>11/12/2013</dd>
                    <dt>GENDER</dt>
                    <dd>Male</dd>
                  </dl>
                </div>-->
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      
                      <tr>
                        <td>Email: </td>
                        <td><%= current_user.email %></td>
                      </tr>
                      
              
                    </tbody>
                  </table>
                  
                 <a><%= link_to "Apply for Conference" , new_conference_path, class: "btn btn-primary" %></a>
                 <a><%= link_to "Applications" , conferences_path, class: "btn btn-primary" %></a>
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                        <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </span>
                    </div>
            
          </div>
        </div>
      </div>
    </div>