config/routes.rb
Rails.application.routes.draw do
  
  resources :messages, only: [:new, :create]

  resources :contacts, only: [:new, :create]
  post 'contacts/new'
  resources :projects
  devise_for :users, controllers: { sessions: "users/sessions" }

  get 'confrencedet/main'

  get 'confrencedet/speakers'

  get 'confrencedet/fees'

  get 'confrencedet/presentation'

  get 'confrencedet/venue'
  get 'confrencedet/advert'

  get 'confrencedet/sponsorship'

  get 'confrencedet/abstractdetails'

  resources :abstracts
  resources :sponsors
  resources :conferences do
      resources :papers, except: [:show, :index]
  end

  get 'welcome/main'
  get 'welcome/donation'
  
  get 'welcome/profile'

  get 'welcome/index'
  get 'welcome/about'
  

 root 'welcome#index'

end

app/controllers/confrencedet_controller.rb
class ConfrencedetController < ApplicationController
  def main
  end

  def speakers
  end

  def fees
  end

  def presentation
  end

  def venue
  end

  def sponsorship
  end

  def abstractdetails
  end
  
  def advert
  end
end

app/helpers/confrencedet_helper.rb
module ConfrencedetHelper
end

app/views/confrencedet/_sidebar.html.erb
  <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Conference 
                    <small>Details</small>
                </h1>
                <ol class="breadcrumb">
                    <li class="active"><%= link_to "Apply to conference", new_conference_path %></li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Sidebar Column -->
            <div class="col-md-3">
                <div class="list-group">
                    <a><%= link_to "Home", confrencedet_main_path , class: "list-group-item list-group-item-info" %></a>
                    <a><%= link_to "Apply to Conference", new_conference_path , class: "list-group-item list-group-item-success" %></a>
                    <a><%= link_to "Presentation", confrencedet_presentation_path, class: "list-group-item list-group-item-info" %></a>
                    <a><%= link_to "Sponsorship", confrencedet_sponsorship_path, class: "list-group-item list-group-item-info" %></a>
                    <a><%= link_to "Speakers", confrencedet_speakers_path, class: "list-group-item list-group-item-info" %></a>
                    <a><%= link_to "Venue/Accomodation", confrencedet_venue_path, class: "list-group-item list-group-item-info" %></a>
                    <a><%= link_to "Advertisment", confrencedet_advert_path, class: "list-group-item list-group-item-info" %></a>
                    <a><%= link_to "Fees/ Payment", confrencedet_fees_path, class: "list-group-item list-group-item-info" %></a>
                    <a><%= link_to "Abstarct Information", confrencedet_abstractdetails_path, class: "list-group-item list-group-item-info" %></a>
                  
                </div>
            </div>
           
       

   

app/views/confrencedet/abstractdetails.html.erb
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <%= render 'sidebar' %>
        
            <div class="col-md-9">
<h2>STEM ACCESS FOR ALL IRRESPECTIVE OF SPECIAL NEEDS <%= link_to "Submit Abstract Here", new_conference_path %></h2>
<p>The Science and Technology for Nigeria Persons with Special Needs Initiative invites you to share your research findings, tested strategies and solutions on STEM access to persons with special needs. This conference will bring together professionals in the various area of special needs and others who provide services, education or programme.</br>
</br>
We are especially interested in presentations aimed at but not limited to:
<ul>
    
<li>Strategies and resources supporting STEM access to learners with visual impairment</li>	
<li>Strategies and resources supporting STEM access to learners with Hearing impairment</li>
<li>Strategies and resources supporting STEM access to learners with reduced physical impairment</li>
<li>Tested resources for full inclusion of learners with special needs in STEM</li> 
<li>Research on Sign language for STEM Access for SEN</li>
<li>Research on UEB, Nemeth and STEM </li>
</ul></br>

<strong>How to submit your Abstract/Paper</strong></br>
All abstract are due for submission by 10th March, 2016. Acceptance notification of the abstract will be provided within a week of submission and the full paper is due on or before 10th March, 2016. Multiple abstract can be submitted.</br>
All submissions should be attached in an email to admin@scitec4sen.com</p>
 </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/confrencedet/advert.html.erb
 <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <%= render 'sidebar' %>
        
            <div class="col-md-9">
<h2>Advertisements in STEM ACCESS 4 SEN Conference proceedings</h2>
<p>Advertisement opportunities in the STEM ACCESS 4 SEN conference proceedings are available for government, corporate, manufacturers, vendors and nonprofit agencies. Advertisement slots are limited and available on a first-come-first-served basis. Applications for advertisements must be received by 20 March, 2016 Advertisements are available in full colour as follows:
<strong></br></br>	Full A4 page 			USD 500
</br>	Half A4 page			USD 300
</br> Quarter A4 page		USD 200 </br></br></strong>

To request an Advertisement Application Form, email admin@scitec4sen.org or complete the form here. Remember to send a copy of the evidence of payment to admin@scitec4sen.org and you will receive an acknowledgement receipt for the payment. 
</p>
 </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/confrencedet/fees.html.erb
   <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <%= render 'sidebar' %>
         <div class="col-md-9">
 <div class="panel panel-default">
                        <div class="panel-heading">
                            Fees
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Presentation Type</th>
                                            <th>Early bird up till <br>March 10, 2016 <br>USD</th>
                                            <th>Early bird up till <br>March 10, 2016 <br>NAIRA</th>
                                            <th>REGULAR After <br> March 10, 2016 <br>USD</th>
                                            <th>REGULAR After <br> March 10, 2016 <br>NAIRA</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="success">
                                            <td>Poster/Oral</td>
                                            <td>250</td>
                                            <td>50,000</td>
                                            <td>300</td>
                                            <td>60,000</td>
                                        </tr>
                                        <tr class="info">
                                            <td>Virtual</td>
                                            <td>150</td>
                                            <td>30,000</td>
                                            <td>200</td>
                                            <td>40,000</td>
                                        </tr>
                                        <tr class="warning">
                                            <td>Additional paper</td>
                                            <td>75</td>
                                            <td>15,000</td>
                                            <td>100</td>
                                            <td>20,000</td>
                                        </tr>
                                        <tr class="success">
                                           <td>Student</td>
                                            <td>100</td>
                                            <td>20,000</td>
                                            <td>150</td>
                                            <td>30,000</td>
                                        </tr>
                                        <tr class="warning">
                                           <td>Primary School Teachers</td>
                                            <td>200</td>
                                            <td>40,000</td>
                                            <td>250</td>
                                            <td>50,000</td>
                                        </tr>
                                        <tr class="success">
                                           <td>Secondary School Teachers</td>
                                            <td>200</td>
                                            <td>40,000</td>
                                            <td>250</td>
                                            <td>50,000</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                            <div class="well">
                               <strong> Cancellation Policy</strong><br>
<small>Attendance to the STEM ACCESS Annual Conference 2016 is on a first come, first serve basis. The conference secretariat reserves the right to decline participation due to space limitations. An early completion of the registration form and transfer of payments are strongly encouraged.

A ninety percent refund (80%) of the registration fee is guaranteed for cancellations made before 1st May 2016. 

A fifty percent refund (50%) will be made from 2nd May until the date of the conference (7th August 2016).</small>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                 </div>
        <!-- /.row -->

        <hr>

app/views/confrencedet/main.html.erb
  <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <%= render 'sidebar' %>
        
            <div class="col-md-9">
                <h2>International Conference August, 2016</h2>
                <p>STEM ACCESS FOR ALL IRRESPECTIVE OF SPECIAL NEEDS
The Science and Technology for Nigeria Persons with Special Needs Initiative invites you to share your research findings, tested strategies and solutions on STEM access to persons with special needs. This conference will bring together professionals in the various area of special needs, sciences, engineering and others who provide services, education or programme for learners with special needs. See call for abstract/paper menu for further details</p>
            <div class="well">
                <h3><%= link_to "Apply for Confererence" , new_conference_path, class: "btn btn-success" %><br><strong>Important Dates</strong></h3>
                <h3>Conference Dates: August 7-12, 2016</h3>
<h3> Presentation Dates: August 9-11, 2016</h3>
<h3>Pre-Conference workshop : August 8, 2016</h3>
<h3>Early Payment Discount: June, 15, 2016 <strong>(Extended)</strong></h3>
<h3>Abstract/paper submission  NOW OPEN</h3>
<h3>Final abstracts/papers due: June 15, 2016 <strong>(Extended)</strong></h3> 
<h3>Optional Tour Dates: August 11 and 12, 2016</h3>
            </div>
            </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/confrencedet/presentation.html.erb
  <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <%= render 'sidebar' %>
        
            <div class="col-md-9">
                <h3>Presentation Format</h3>
                <p>Presentation format shall be in three forms: Oral, Virtual and Poster.</br>
<strong> Oral/Standard presentations</strong></br>
scheduled for 15-20 minutes per presentation. </br>
<strong>Virtual presentations</strong></br>
Can’t attend the conference in person? A virtual presentation allows your Powerpoint, or video to be presented for you at the conference. You will receive a complete conference package after the conference through post.</br>
<strong>Interactive sessions /Workshop</strong></br>
Interactive sessions/Workshop presentations is addressed to those whose presentation involve hands-on activities. This is more encouraged because of the nature of the conference. 1-2 hour session will be allocated to one presentation depending on requirement
</br>
<strong>Poster presentations</strong></br>
Poster presentations is addressed to those who prefer one-one presentation on display. Poster will be displayed as schedule on the conference programme.
</p>

<div class="well">All accepted papers for workshop, oral, virtual and poster presentations will be included in the Conference Proceedings published by SCITEC4SEN with ISBN and ISSN codes.
This publication will be reviewed for inclusion in relevant SciTec4sen Journals online and hard copy versions.
</div>
            </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/confrencedet/speakers.html.erb
  <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <%= render 'sidebar' %>
        
                <div class="col-md-4 img-portfolio">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/700x400" alt="">
                </a>
                <h3>
                    <a href="portfolio-item.html">Dr Gary Supalo</a>
                </h3>
                <p>
                    Dr. Cary Supalo is an Assistant Professor in Chemical Education at Purdue University in West Lafayette, Indiana. 
                    He has a passion for problem solving and making science accessible for all students with disabilities. Blind since birth, Cary Supalo earned his undergraduate degree from Purdue University and his Master’s and PhD in Chemistry from Pennsylvania State University. He is the founder and CEO of a company called Independence Science.Dr. 
                    Supalo has developed and field-tested devices and methods for making Chemistry accessible for all students with disabilities including those who are blind. His research interests include modification of science curricula and teaching methodologies, along with further development of assistive technologies
                </p>
            </div>
            <div class="col-md-4 img-portfolio">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/700x400" alt="">
                </a>
                <h3>
                    <a href="portfolio-item.html">Prof. Kamoru Usman</a>
                </h3>
                <p>
                    Prof. Kamoru Usman is the Provost of the Federal College of Education (Special) Oyo. 
                    His academic qualifications include a Bachelors Degree in Science Education, a Masters Degree in Education (Mathematics) 
                    and a Doctorate Degree in Education (Mathematics),” Prof. Usman was the Associate Dean of the Faculty of Education, 
                    University of Nigeria, Nsukka, before his new appointment as PROVOST Federal College of Education (Special) Oyo. Nigeria.
                </p>
            </div>
            <div class="col-md-4 img-portfolio">
                <a href="portfolio-item.html">
                    <img class="img-responsive img-hover" src="http://placehold.it/700x400" alt="">
                </a>
                <h3>
                    <a href="portfolio-item.html">Adebowale Ogunjirin</a>
                </h3>
                <p>
                    Adebowale Ogunjirin, Nigeria-born, became deaf at age 9 due to illness. 
                    He graduated from  the University of Ibadan, in 1995 with a bachelor’s degree in Pharmacology. He holds a master’s degree in Pharmaceutics and Pharmaceutical Technology from the University of Lagos, Nigeria.
Ogunjirin also has a Ph. D in Pharmacology from Howard University, United States in 2005. 
He is currently an assistant Professor of Biology at The Gallaudet University, United States.
                </p>
            </div>
            </div>
        <!-- /.row -->

        <hr>

app/views/confrencedet/sponsorship.html.erb
  <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <%= render 'sidebar' %>
        
            <div class="col-md-4">
                <div class="panel panel-default text-center">
                    <div class="panel-heading">
                        <h3 class="panel-title">Diamond</h3>
                    </div>
                    <div class="panel-body">
                        <span class="price">USD 7,000</span>
                        <span class="period">Exclusive to one company/agency</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Conferment of partner status in hosting the STEM ACCESS 4 SEN Conference</li>
                        <li class="list-group-item">A table in the registration area to promote your company and products</li>
                        <li class="list-group-item">One hour workshop with the conference participants</li>
                        <li class="list-group-item">One free exhibition booth and 3 conference pass</li>
                        <li class="list-group-item">Recognition as Diamond Sponsor at Opening and Closing ceremonies</li>
                        <li class="list-group-item">Opportunity to address participants at Opening Ceremony</li>
                        <li class="list-group-item">Opportunity to chair one Keynote Session</li>
                        <li class="list-group-item">Opportunity to display company banner at Opening and Closing ceremonies</li>
                        <li class="list-group-item">Full A4 page  advertisement and company profile in the Conference Proceeding </li>
                        <li class="list-group-item">Your company logo displayed on the looping power point presentation that is played during breaks in each of the conference rooms</li>
                        <li class="list-group-item">Recognition on the Scitec4sen website including links to your website</li>
                        <li class="list-group-item">Sponsor’s promotional items placed in all Conference Bags</li>
                        <li class="list-group-item">A certificate of Appreciation for your contribution towards the conference</li>
                        <li class="list-group-item"><%= button_to "Apply", new_sponsor_path, class: "btn btn-primary" %>
                        </li>
                    </ul>
                </div>
                </div>
                <div class="col-md-4">
                <div class="panel panel-default text-center">
                    <div class="panel-heading">
                        <h3 class="panel-title">Gold</h3>
                    </div>
                    <div class="panel-body">
                        <span class="price">USD 5000</span>
                        <span class="period">Exclusive to 3 Companies</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Conferment of partner status in hosting the STEM ACCESS 4 SEN Conference</li>
                        <li class="list-group-item">A table in the registration area to promote your company and products</li>
                        <li class="list-group-item">One hour workshop with the conference participants</li>
                        <li class="list-group-item">Exclusive sponsor of the Book of Abstract and Conference programme</li>
                        <li class="list-group-item">One free exhibition booth and 2 conference pass</li>
                        <li class="list-group-item">Recognition as Gold Sponsor at Opening and Closing ceremonies</li>
                        <li class="list-group-item">Opportunity to address participants at Opening Ceremony</li>
                        <li class="list-group-item">Opportunity to chair one Keynote Session</li>
                        <li class="list-group-item">Opportunity to display company banner at Opening and Closing ceremonies</li>
                        <li class="list-group-item">Full A4 page  advertisement and company profile in the Conference Proceeding </li>
                        <li class="list-group-item">Recognition on the Scitec4sen website including links to your website</li>
                        <li class="list-group-item">Sponsor’s promotional items placed in all Conference Bags</li>
                        <li class="list-group-item">A certificate of Appreciation for your contribution towards the conference</li>
                        <li class="list-group-item"><%= button_to "Apply", new_sponsor_path, class: "btn btn-primary" %>
                        </li>
                    </ul>
                </div>
                </div>
                <div class="col-md-4">
                <div class="panel panel-default text-center">
                    <div class="panel-heading">
                        <h3 class="panel-title">Bronze</h3>
                    </div>
                    <div class="panel-body">
                        <span class="price">USD 2500</span>
                        <span class="period">Exclusive to 4 Companies</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">Conferment of partner status in hosting the STEM ACCESS 4 SEN Conference</li>
<li class="list-group-item">A table in the registration area to promote your company and products</li>
<li class="list-group-item">One free exhibition booth and 1 conference pass</li>
<li class="list-group-item">Recognition as Bronze Sponsor at Opening and Closing ceremonies</li>
<li class="list-group-item">Opportunity to display company banner at Opening and Closing ceremonies</i>
<li class="list-group-item">Quarter of A4 page advertisement and company profile in the Conference Proceeding</li> 
<li class="list-group-item">Recognition on the Scitec4sen website including links to your website</li>
<li class="list-group-item">Sponsor’s promotional items/flyer placed in all Conference Bags</li>
<li class="list-group-item">A certificate of Appreciation for your contribution towards the conference</li>
                        <li class="list-group-item"><%= link_to "Apply", new_sponsor_path, class: "btn btn-primary" %>
                        </li>
                    </ul>
                </div>
                </div>
        </div>
        <!-- /.row -->

        <hr>

app/views/confrencedet/venue.html.erb
  <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <%= render 'sidebar' %>
        
            <div class="col-md-9">
                <h2>Venue</h2>
<p><a href="http://rockviewhotels.com/">ROCKVIEW HOTELS</a></br>
No.194/196, Adetokunbo Ademola Crescent,</br>
Wuse II, </br>
Abuja, </br>
 Nigeria</p>
 
 </div>
        </div>
        <!-- /.row -->

        <hr>